### ISSUE TITLE
Hi dar

### ISSUE THREAD

**Issue by whippingdot** [darkdarcool/nvim#1]
I saw you archived the organization - its been a long time bro its giving me flashbacks. It was so fun back then - making horrible projects and chatting and just doing random stuff.
Did you see the updates to repilt? They made it much more company focussed and less community focussed - everything is paid and gone.
Watcha doing rn. I haven't coded in a while but will get back into Unity and C# in a few months. I used to grind leetcode a few months ago.

**Comment by darkdarcool** [comment]
Hi whippingdot!
I was just cleaning out the orgs I was apart of, and stumbled back upon the replit org. Def brought back memories, and I decided to archive it instead of deleting it. 
I did see the updates the replit. I don't support the massive shift to AI driven development and company focused deployment and editing, so I don't really use it anymore.
Lately I've just been focusing on school and coding small side projects here and there that I don't push to GitHub.

**Comment by whippingdot** [comment]
mb i never replied lol.
Do you have an insta?
Also yea thanks for not deleting the org? If you deleted it we would've lost everything so like... Also yea same opinion on replit.
I am in 11th what grade are you in? I presume 12th or 10th - if so how are you doing

**Comment by darkdarcool** [comment]
I do have instagram, but it's a personal account so I'm not really comfortable giving it out. I'm also in 11th grade, and I'm doing fine
